server:
  port: 8080
  servlet:
    contextPath: /SRM
---
spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.web.servlet.error.ErrorMvcAutoConfiguration
---
spring:
  profiles: local,default
